apiVersion: v1
kind: Service
metadata:
  name: xpanse
  namespace: xpanse
  labels:
    app: xpanse
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: xpanse