apiVersion: apps/v1
kind: Deployment
metadata:
  name: xpanse
  namespace: xpanse
  labels:
    app: xpanse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xpanse
  template:
    metadata:
      labels:
        app: xpanse
    spec:
      containers:
        - name: xpanse
          image: xpanse:1.0.0-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: huaweicloud
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /xpanse/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /xpanse/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10